Logger:
    Cores:
    - Name : stderr
      EncoderLevel: production
      Path: /dev/stderr
      Level : 0
    - Name : logfile
      EncoderLevel: production
      Path: "../tmp/log"
      Level : -1
Service:
  Timeout: 10s